package schemata

import (
	hc_ad "cueniform.com/collector/schemata/providers/hashicorp/ad/metadata"
	hc_archive "cueniform.com/collector/schemata/providers/hashicorp/archive/metadata"
	hc_aws "cueniform.com/collector/schemata/providers/hashicorp/aws/metadata"
	hc_awscc "cueniform.com/collector/schemata/providers/hashicorp/awscc/metadata"
	hc_azuread "cueniform.com/collector/schemata/providers/hashicorp/azuread/metadata"
	hc_azurerm "cueniform.com/collector/schemata/providers/hashicorp/azurerm/metadata"
	hc_azurestack "cueniform.com/collector/schemata/providers/hashicorp/azurestack/metadata"
	hc_boundary "cueniform.com/collector/schemata/providers/hashicorp/boundary/metadata"
	hc_cloudinit "cueniform.com/collector/schemata/providers/hashicorp/cloudinit/metadata"
	hc_consul "cueniform.com/collector/schemata/providers/hashicorp/consul/metadata"
	hc_dns "cueniform.com/collector/schemata/providers/hashicorp/dns/metadata"
	hc_external "cueniform.com/collector/schemata/providers/hashicorp/external/metadata"
	hc_google "cueniform.com/collector/schemata/providers/hashicorp/google/metadata"
	hc_googleworkspace "cueniform.com/collector/schemata/providers/hashicorp/googleworkspace/metadata"
	hc_hcp "cueniform.com/collector/schemata/providers/hashicorp/hcp/metadata"
	hc_hcs "cueniform.com/collector/schemata/providers/hashicorp/hcs/metadata"
	hc_helm "cueniform.com/collector/schemata/providers/hashicorp/helm/metadata"
	hc_http "cueniform.com/collector/schemata/providers/hashicorp/http/metadata"
	hc_kubernetes "cueniform.com/collector/schemata/providers/hashicorp/kubernetes/metadata"
	hc_local "cueniform.com/collector/schemata/providers/hashicorp/local/metadata"
	hc_nomad "cueniform.com/collector/schemata/providers/hashicorp/nomad/metadata"
	hc_null "cueniform.com/collector/schemata/providers/hashicorp/null/metadata"
	hc_opc "cueniform.com/collector/schemata/providers/hashicorp/opc/metadata"
	hc_oraclepaas "cueniform.com/collector/schemata/providers/hashicorp/oraclepaas/metadata"
	hc_random "cueniform.com/collector/schemata/providers/hashicorp/random/metadata"
	hc_salesforce "cueniform.com/collector/schemata/providers/hashicorp/salesforce/metadata"
	hc_template "cueniform.com/collector/schemata/providers/hashicorp/template/metadata"
	hc_tfe "cueniform.com/collector/schemata/providers/hashicorp/tfe/metadata"
	hc_time "cueniform.com/collector/schemata/providers/hashicorp/time/metadata"
	hc_tls "cueniform.com/collector/schemata/providers/hashicorp/tls/metadata"
	hc_vault "cueniform.com/collector/schemata/providers/hashicorp/vault/metadata"
	hc_vsphere "cueniform.com/collector/schemata/providers/hashicorp/vsphere/metadata"
	p_github "cueniform.com/collector/schemata/providers/integrations/github/metadata"
)

provider: {
	hashicorp: {
		"ad":              hc_ad
		"archive":         hc_archive
		"aws":             hc_aws
		"awscc":           hc_awscc
		"azuread":         hc_azuread
		"azurerm":         hc_azurerm
		"azurestack":      hc_azurestack
		"boundary":        hc_boundary
		"cloudinit":       hc_cloudinit
		"consul":          hc_consul
		"dns":             hc_dns
		"external":        hc_external
		"google":          hc_google
		"googleworkspace": hc_googleworkspace
		"hcp":             hc_hcp
		"hcs":             hc_hcs
		"helm":            hc_helm
		"http":            hc_http
		"kubernetes":      hc_kubernetes
		"local":           hc_local
		"nomad":           hc_nomad
		"null":            hc_null
		"opc":             hc_opc
		"oraclepaas":      hc_oraclepaas
		"random":          hc_random
		"salesforce":      hc_salesforce
		"template":        hc_template
		"tfe":             hc_tfe
		"time":            hc_time
		"tls":             hc_tls
		"vault":           hc_vault
		"vsphere":         hc_vsphere
	}
	integrations: github: p_github
}
