package desiderata

provider: hashicorp: vault: {
	id: "hashicorp/vault"
	versions: [{
		version: "2.14.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}]
	}, {
		version: "3.4.1"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}]
	}, {
		version: "1.1.0"
		protocols: ["4"]
		platforms: [{
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}]
	}, {
		version: "2.19.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "windows"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "amd64"
		}]
	}, {
		version: "1.1.4"
		protocols: ["4"]
		platforms: [{
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}]
	}, {
		version: "3.10.0"
		protocols: ["5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "amd64"
		}]
	}, {
		version: "2.17.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}]
	}, {
		version: "2.23.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}]
	}, {
		version: "1.1.2"
		protocols: ["4"]
		platforms: [{
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "386"
		}]
	}, {
		version: "2.19.1"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}]
	}, {
		version: "3.11.0"
		protocols: ["5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}]
	}, {
		version: "2.21.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "386"
		}]
	}, {
		version: "2.5.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}]
	}, {
		version: "1.3.0"
		protocols: ["4"]
		platforms: [{
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}]
	}, {
		version: "2.3.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "386"
		}]
	}, {
		version: "2.10.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}]
	}, {
		version: "2.7.1"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}]
	}, {
		version: "3.8.0"
		protocols: ["5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}]
	}, {
		version: "1.9.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}]
	}, {
		version: "2.24.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}]
	}, {
		version: "3.8.2"
		protocols: ["5.0"]
		platforms: [{
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}]
	}, {
		version: "3.2.1"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}]
	}, {
		version: "1.4.1"
		protocols: ["4"]
		platforms: [{
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "amd64"
		}]
	}, {
		version: "2.4.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}]
	}, {
		version: "2.15.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}]
	}, {
		version: "1.8.0"
		protocols: ["4.0"]
		platforms: [{
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}]
	}, {
		version: "3.4.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}]
	}, {
		version: "3.8.1"
		protocols: ["5.0"]
		platforms: [{
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "386"
		}]
	}, {
		version: "3.3.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}]
	}, {
		version: "2.12.2"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}]
	}, {
		version: "2.22.1"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}]
	}, {
		version: "1.1.3"
		protocols: ["4"]
		platforms: [{
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}]
	}, {
		version: "1.3.1"
		protocols: ["4"]
		platforms: [{
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "386"
		}]
	}, {
		version: "2.6.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}]
	}, {
		version: "3.5.0"
		protocols: ["5.0"]
		platforms: [{
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}]
	}, {
		version: "3.9.0"
		protocols: ["5.0"]
		platforms: [{
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}]
	}, {
		version: "2.1.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}]
	}, {
		version: "2.12.1"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}]
	}, {
		version: "0.1.0"
		protocols: ["4"]
		platforms: [{
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}]
	}, {
		version: "2.22.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "linux"
			arch: "386"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm64"
		}]
	}, {
		version: "2.20.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}]
	}, {
		version: "2.9.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "windows"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}]
	}, {
		version: "2.12.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "windows"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}]
	}, {
		version: "2.2.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}]
	}, {
		version: "1.7.0"
		protocols: ["4.0"]
		platforms: [{
			os:   "linux"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}]
	}, {
		version: "3.6.0"
		protocols: ["5.0"]
		platforms: [{
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "amd64"
		}]
	}, {
		version: "3.2.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "amd64"
		}]
	}, {
		version: "1.6.0"
		protocols: ["4.0"]
		platforms: [{
			os:   "windows"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}]
	}, {
		version: "3.12.0"
		protocols: ["5.0"]
		platforms: [{
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}]
	}, {
		version: "2.7.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}]
	}, {
		version: "2.11.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "openbsd"
			arch: "386"
		}]
	}, {
		version: "1.0.0"
		protocols: ["4"]
		platforms: [{
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}]
	}, {
		version: "1.4.0"
		protocols: ["4"]
		platforms: [{
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}]
	}, {
		version: "3.0.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}]
	}, {
		version: "2.8.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}]
	}, {
		version: "3.7.0"
		protocols: ["5.0"]
		platforms: [{
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "amd64"
		}]
	}, {
		version: "1.5.0"
		protocols: ["4.0"]
		platforms: [{
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}]
	}, {
		version: "3.9.1"
		protocols: ["5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}]
	}, {
		version: "3.1.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}]
	}, {
		version: "2.18.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}]
	}, {
		version: "2.16.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}]
	}, {
		version: "2.24.1"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}]
	}, {
		version: "3.0.1"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}]
	}, {
		version: "2.13.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}]
	}, {
		version: "2.0.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}]
	}, {
		version: "1.2.0"
		protocols: ["4"]
		platforms: [{
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}]
	}, {
		version: "3.1.1"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}]
	}, {
		version: "3.3.1"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "windows"
			arch: "386"
		}]
	}, {
		version: "1.1.1"
		protocols: ["4"]
		platforms: [{
			os:   "windows"
			arch: "386"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}]
	}]
	warnings: null
}
