package desiderata

provider: hashicorp: tfe: {
	id: "hashicorp/tfe"
	versions: [{
		version: "0.29.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm64"
		}]
	}, {
		version: "0.2.0"
		protocols: ["4"]
		platforms: [{
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}]
	}, {
		version: "0.14.1"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "linux"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}]
	}, {
		version: "0.38.0"
		protocols: ["5.0"]
		platforms: [{
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}]
	}, {
		version: "0.16.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "linux"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}]
	}, {
		version: "0.10.1"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}]
	}, {
		version: "0.34.0"
		protocols: ["5.0"]
		platforms: [{
			os:   "windows"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}]
	}, {
		version: "0.6.0"
		protocols: ["4"]
		platforms: [{
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}]
	}, {
		version: "0.1.0"
		protocols: ["4"]
		platforms: [{
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}]
	}, {
		version: "0.32.1"
		protocols: ["5.0"]
		platforms: [{
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}]
	}, {
		version: "0.12.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "linux"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}]
	}, {
		version: "0.22.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}]
	}, {
		version: "0.20.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}]
	}, {
		version: "0.21.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "linux"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}]
	}, {
		version: "0.11.4"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}]
	}, {
		version: "0.17.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}]
	}, {
		version: "0.25.2"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "386"
		}]
	}, {
		version: "0.11.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}]
	}, {
		version: "0.9.1"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "windows"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}]
	}, {
		version: "0.40.0"
		protocols: ["5.0"]
		platforms: [{
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}]
	}, {
		version: "0.30.2"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}]
	}, {
		version: "0.26.0"
		protocols: ["5.0"]
		platforms: [{
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "amd64"
		}]
	}, {
		version: "0.25.3"
		protocols: ["5.0"]
		platforms: [{
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}]
	}, {
		version: "0.30.1"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "amd64"
		}]
	}, {
		version: "0.10.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}]
	}, {
		version: "0.8.0"
		protocols: ["4.0"]
		platforms: [{
			os:   "windows"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}]
	}, {
		version: "0.33.0"
		protocols: ["5.0"]
		platforms: [{
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "amd64"
		}]
	}, {
		version: "0.28.1"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "amd64"
		}]
	}, {
		version: "0.9.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}]
	}, {
		version: "0.36.1"
		protocols: ["5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}]
	}, {
		version: "0.36.0"
		protocols: ["5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm64"
		}]
	}, {
		version: "0.25.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "darwin"
			arch: "arm64"
		}]
	}, {
		version: "0.12.1"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}]
	}, {
		version: "0.37.0"
		protocols: ["5.0"]
		platforms: [{
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "arm64"
		}]
	}, {
		version: "0.39.0"
		protocols: ["5.0"]
		platforms: [{
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}]
	}, {
		version: "0.16.2"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm"
		}]
	}, {
		version: "0.7.0"
		protocols: ["4.0"]
		platforms: [{
			os:   "windows"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}]
	}, {
		version: "0.27.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "arm64"
		}]
	}, {
		version: "0.14.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "solaris"
			arch: "amd64"
		}]
	}, {
		version: "0.41.0"
		protocols: ["5.0"]
		platforms: [{
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}]
	}, {
		version: "0.19.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "386"
		}]
	}, {
		version: "0.7.1"
		protocols: ["4.0"]
		platforms: [{
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "386"
		}]
	}, {
		version: "0.26.1"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm64"
		}]
	}, {
		version: "0.27.1"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}]
	}, {
		version: "0.18.1"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}]
	}, {
		version: "0.15.1"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "windows"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}]
	}, {
		version: "0.32.0"
		protocols: ["5.0"]
		platforms: [{
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "amd64"
		}]
	}, {
		version: "0.8.2"
		protocols: ["4.0"]
		platforms: [{
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "386"
		}]
	}, {
		version: "0.5.0"
		protocols: ["4"]
		platforms: [{
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "openbsd"
			arch: "386"
		}]
	}, {
		version: "0.31.0"
		protocols: ["5.0"]
		platforms: [{
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}]
	}, {
		version: "0.16.1"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}]
	}, {
		version: "0.11.2"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}]
	}, {
		version: "0.24.0"
		protocols: ["5.0"]
		platforms: [{
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}]
	}, {
		version: "0.35.0"
		protocols: ["5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}]
	}, {
		version: "0.25.1"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "arm64"
		}]
	}, {
		version: "0.15.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}]
	}, {
		version: "0.23.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}]
	}, {
		version: "0.4.0"
		protocols: ["4"]
		platforms: [{
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "openbsd"
			arch: "386"
		}]
	}, {
		version: "0.11.1"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}]
	}, {
		version: "0.17.1"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}]
	}, {
		version: "0.28.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}]
	}, {
		version: "0.13.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "386"
		}]
	}, {
		version: "0.11.3"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "linux"
			arch: "arm"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "amd64"
		}]
	}, {
		version: "0.30.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "amd64"
		}]
	}, {
		version: "0.18.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}]
	}, {
		version: "0.3.0"
		protocols: ["4"]
		platforms: [{
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}]
	}, {
		version: "0.8.1"
		protocols: ["4.0"]
		platforms: [{
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}]
	}]
	warnings: null
}
