package desiderata

provider: hashicorp: nomad: {
	id: "hashicorp/nomad"
	versions: [{
		version: "1.4.4"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}]
	}, {
		version: "1.0.0"
		protocols: ["4"]
		platforms: [{
			os:   "linux"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}]
	}, {
		version: "1.4.9"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}]
	}, {
		version: "1.1.0"
		protocols: ["4"]
		platforms: [{
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}]
	}, {
		version: "1.4.10"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm64"
		}]
	}, {
		version: "1.3.0"
		protocols: ["4"]
		platforms: [{
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}]
	}, {
		version: "1.4.18"
		protocols: ["5.0"]
		platforms: [{
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm64"
		}]
	}, {
		version: "1.4.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "solaris"
			arch: "amd64"
		}]
	}, {
		version: "0.1.0"
		protocols: ["4"]
		platforms: [{
			os:   "windows"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}]
	}, {
		version: "1.4.15"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "arm64"
		}]
	}, {
		version: "1.4.2"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}]
	}, {
		version: "1.2.0"
		protocols: ["4"]
		platforms: [{
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "solaris"
			arch: "amd64"
		}]
	}, {
		version: "1.4.14"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "windows"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm64"
		}]
	}, {
		version: "1.4.6"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}]
	}, {
		version: "1.4.13"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm"
		}]
	}, {
		version: "1.4.19"
		protocols: ["5.0"]
		platforms: [{
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}]
	}, {
		version: "1.4.16"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm64"
		}]
	}, {
		version: "1.4.8"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}]
	}, {
		version: "1.4.12"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}]
	}, {
		version: "1.4.1"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}]
	}, {
		version: "1.4.7"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}]
	}, {
		version: "1.4.17"
		protocols: ["5.0"]
		platforms: [{
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "arm64"
		}]
	}, {
		version: "1.4.11"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}]
	}, {
		version: "1.4.3"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}]
	}, {
		version: "1.4.5"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}]
	}]
	warnings: null
}
