package desiderata

provider: hashicorp: consul: {
	id: "hashicorp/consul"
	versions: [{
		version: "2.8.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}]
	}, {
		version: "2.17.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}]
	}, {
		version: "1.0.0"
		protocols: ["4"]
		platforms: [{
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}]
	}, {
		version: "2.0.0"
		protocols: ["4"]
		platforms: [{
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "386"
		}]
	}, {
		version: "2.1.0"
		protocols: ["4"]
		platforms: [{
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}]
	}, {
		version: "2.16.1"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "windows"
			arch: "386"
		}]
	}, {
		version: "2.6.1"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}]
	}, {
		version: "2.11.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}]
	}, {
		version: "2.16.2"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "386"
		}]
	}, {
		version: "2.2.0"
		protocols: ["4"]
		platforms: [{
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}]
	}, {
		version: "2.3.0"
		protocols: ["4.0"]
		platforms: [{
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}]
	}, {
		version: "2.4.0"
		protocols: ["4.0"]
		platforms: [{
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}]
	}, {
		version: "2.12.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "arm64"
		}]
	}, {
		version: "2.15.1"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}]
	}, {
		version: "2.10.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm64"
		}]
	}, {
		version: "2.15.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}]
	}, {
		version: "0.1.0"
		protocols: ["4"]
		platforms: [{
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}]
	}, {
		version: "2.14.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}]
	}, {
		version: "2.5.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}]
	}, {
		version: "2.7.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}]
	}, {
		version: "2.10.1"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}]
	}, {
		version: "1.1.0"
		protocols: ["4"]
		platforms: [{
			os:   "linux"
			arch: "arm"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}]
	}, {
		version: "2.16.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "386"
		}]
	}, {
		version: "2.13.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "linux"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "arm64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "386"
		}]
	}, {
		version: "2.6.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "windows"
			arch: "386"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "windows"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "freebsd"
			arch: "386"
		}]
	}, {
		version: "2.9.0"
		protocols: ["4.0", "5.0"]
		platforms: [{
			os:   "openbsd"
			arch: "amd64"
		}, {
			os:   "darwin"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "386"
		}, {
			os:   "linux"
			arch: "arm"
		}, {
			os:   "solaris"
			arch: "amd64"
		}, {
			os:   "linux"
			arch: "amd64"
		}, {
			os:   "freebsd"
			arch: "amd64"
		}, {
			os:   "openbsd"
			arch: "386"
		}, {
			os:   "freebsd"
			arch: "arm"
		}, {
			os:   "windows"
			arch: "386"
		}, {
			os:   "linux"
			arch: "386"
		}, {
			os:   "windows"
			arch: "amd64"
		}]
	}]
	warnings: null
}
