name: main/merge/develop

"on":
  push:
    branches: [ "develop" ]

concurrency: "main"

jobs:
  test_and_merge:
    name: "Merge develop into new"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
    steps:
      - name: "Check out code"
        uses: "actions/checkout@v3"
      - name: "Install CUE"
        uses: "cue-lang/setup-cue@0be332bb74c8a2f07821389447ba3163e2da3bfb"
        with:
          version: "latest"
      - name: "Run tests"
        run: |
          make --version
          make test
      - name: "Check out code"
        uses: "actions/checkout@v3"
        with:
          ref: "new"
          fetch-depth: 0
      - name: "Check if `develop` has been rebased onto `new`"
        run: "git merge-base --is-ancestor new origin/develop"
      - name: "Merge develop into new"
        run: |
          git merge origin/develop --ff-only
          git push
