name: scheduled/main/update-desiderata

"on":
  schedule:
    - cron: "13 3 * * *"
  workflow_dispatch:
    inputs:
      delay:
        description: "(int) The delay in seconds between API requests"
        type: "number"
        required: false

concurrency: "main"

env:
  TF_IN_AUTOMATION: yes it is
  TF_INPUT: 0

defaults:
  run:
    shell: nice -n 19 ionice --class 3 bash --noprofile --norc -exo pipefail {0}

jobs:
  poll_and_commit:
    name: "Update desiderata"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
    env:
      DELAY: "${{ inputs.delay || 5 }}"

    steps:

      - name: "Check out code"
        uses: "actions/checkout@v3"
        with:
          fetch-depth: 0

      - name: "Install CUE"
        uses: "cue-lang/setup-cue@0be332bb74c8a2f07821389447ba3163e2da3bfb"
        with:
          version: "v0.6.0-alpha.1"

      - name: "Install Terraform"
        uses: "hashicorp/setup-terraform@v2"
        with:
          terraform_version: "1.4.x"
          terraform_wrapper: false

      - name: "Poll registry and update desiderata"
        run: "./bin/generate-desiderata-for-all-providers.sh ${DELAY}"

      - name: "Commit and push to main"
        run: |
          git config user.name "[bot] Registry poller"
          git config user.email "<>"

          git add -v desiderata

          if git commit -m "[bot] poller: $(git diff --cached --shortstat desiderata)"; then
            git push -v
          else
            echo "Registry poller: nothing to do"
          fi
