name: scheduled/main/poll-registry-provider-versions

"on":
  schedule: # sync these with inputs.schedule and matrix.cron
    - cron: "13 3 * * *"
    - cron: "23 3 * * *"
    - cron: "33 3 * * *"
    - cron: "43 3 * * *"
    - cron: "53 3 * * *"
  workflow_dispatch:
    inputs:
      schedule:
        description: "A fake scheduled event to test GHA"
        required: true
        type: choice
        options:
          - "13 3 * * *"
          - "23 3 * * *"
          - "33 3 * * *"
          - "43 3 * * *"
          - "53 3 * * *"

concurrency: "main"

jobs:
  poll_and_commit:
    name: "Poll registry for provider versions (${{ matrix.target }})"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        include: # sync these with the bucket definitions in registry/Makefile
          - cron: "13 3 * * *"
            target: "bucket-1"
          - cron: "23 3 * * *"
            target: "bucket-2"
          - cron: "33 3 * * *"
            target: "bucket-3"
          - cron: "43 3 * * *"
            target: "bucket-4"
          - cron: "53 3 * * *"
            target: "bucket-5"
    permissions:
      contents: "write"
    steps:
      - name: "Check out code"
        id: "check"
        if: "( github.event.schedule || github.event.inputs.schedule ) == matrix.cron"
        uses: "actions/checkout@v3"
        with:
          fetch-depth: 0
      - name: "Install CUE"
        if: "steps.check.outcome == 'success'"
        uses: "cue-lang/setup-cue@0be332bb74c8a2f07821389447ba3163e2da3bfb"
        with:
          version: "latest"
      - name: "Run registry tests"
        if: "steps.check.outcome == 'success'"
        run: "make test-registry"
      - name: "Poll registry and serialise responses"
        if: "steps.check.outcome == 'success'"
        run: "make registry REGISTRY_TARGET=${{ matrix.target }}"
      - name: "Commit and push to main"
        if: "steps.check.outcome == 'success'"
        run: |
          git config user.name "[bot] Registry Poller"
          git config user.email "<>"

          git add -v registry

          if git commit -m "Registry poller: new provider versions added"; then
            git push -v
          else
            echo "Registry poller: no new provider versions detected"
          fi
