name: scheduled/main/fetch-missing-provider-schemas

"on":
  schedule: # x7 minutes past each hour, except 03:x7 (which is the poller's hour)
    - cron: "7/10 0,1,2,4-23 * * *"
  workflow_dispatch:
    inputs:
      count:
        description: "Number of schemas to fetch"
        required: false
        type: number
        default: 2

concurrency: "main"

jobs:
  fetch_and_commit:
    name: "Fetch missing provider schemas"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
    env:
      COUNT: "${{ github.event.inputs.count || 7 }}" # FIXME move this default to the repo env
    steps:
      - name: "Check out code"
        uses: "actions/checkout@v3"
        with:
          fetch-depth: 0
      - name: "Install CUE"
        uses: "cue-lang/setup-cue@0be332bb74c8a2f07821389447ba3163e2da3bfb"
        with:
          version: "latest"
      - name: "Run missing-provider-schema-related tests"
        run: "make -C test/one_provider_two_version check"
      - name: "Fetch up to ${{ env.COUNT }} missing provider schemas"
        run: "make missing_schemas COUNT=$COUNT"
      - name: "Commit and push to main"
        run: |
          git config user.name "[bot] Schema Fetcher"
          git config user.email "<>"

          outstanding=$(grep -c ^ missing)
          echo "Schema fetcher: schemas outstanding: $outstanding."

          git add -v schemata/\*.zstd
          fetched=$(git status -s | grep -c ^A)
          echo "Schema fetcher: schemas fetched and added: $fetched."

          git add -v schemata
          added=$(git status -s | grep -c ^A)
          echo "Schema fetcher: new files added: $added."

          if git commit -m "Schema fetcher: $fetched new schemas"; then
            git push -v
          else
            echo "Schema fetcher: git commit failed: assuming no new files; not pushing"
          fi
