name: scheduled/main/fetch-missing-provider-schemas

"on":
  schedule:
#            42 minutes past every hour from 04:42 to 23:42 inclusive
    - cron: "42 4-23 * * *"
  workflow_dispatch:
    inputs:
      count:
        description: "(int) Number of schemas to fetch"
        type: "number"
        default: 20
        required: false
      delay:
        description: "(int) Delay in seconds between each schema being fetched"
        type: "number"
        default: 5
        required: false

concurrency: "main"

env:
  TF_IN_AUTOMATION: yes it is
  TF_INPUT: 0

defaults:
  run:
    shell: nice -n 19 ionice --class 3 bash --noprofile --norc -eo pipefail {0}

jobs:
  fetch_and_commit:
    name: "Fetch provider schemas"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
      issues: "write"
    env:
      DELAY: "${{ inputs.delay || 15 }}"
      COUNT: "${{ inputs.count || 50 }}"
    steps:

      - name: "Check out code"
        uses: "actions/checkout@v3"
        with:
          fetch-depth: 0

      - name: "Install CUE"
        uses: "cue-lang/setup-cue@0be332bb74c8a2f07821389447ba3163e2da3bfb"
        with:
          version: "v0.6.0-alpha.1"

      - name: "Install Terraform"
        uses: "hashicorp/setup-terraform@v2"
        with:
          terraform_version: "1.4.x"
          terraform_wrapper: false

      - name: "Build download list"
        run: "make priorities.txt"

      - name: "Fetch provider schemas (up to ${{ env.COUNT }})"
        env:
          GH_TOKEN: "${{ github.token }}"
        run: "./bin/process-next-N-missing-provider-versions.sh ${COUNT} ${DELAY}"

      - name: "Commit and push to main"
        run: |
          git config user.name "[bot] Schema fetcher"
          git config user.email "<>"

          git add -v schemata/\*.zst
          fetched=$(git status -s | grep -c ^A || true)
          echo "Fetched $fetched schemas"

          git add -v schemata/ errata/
          added=$(git status -s | grep -c ^A || true)
          echo "Added $added files"

          if git commit -m "[bot] fetcher: $fetched new schemas"; then
            git push -v
          else
            echo "Schema fetcher: git commit failed: assuming no new files; not pushing"
          fi
